---
title: "About"
---

I hold a Ph.D. in biochemistry from the University of Victoria. My journey of over 12 years in research has been dedicated to the fascinating realm of mass spectrometry-based techniques, structural proteomics, and bioinformatics. I am an expert in cross-linking mass spectrometry (XL-MS), having developed and applied innovative methods for studying protein structure, dynamics, and interactions in various biological contexts, such as mitochondria, prions, viral and intrinsically disordered proteins. 

I have accumulated a wealth of hands-on lab experience as a proteomics research technician and later as a graduate student at the [University of Victoria Genome British Columbia Proteomics Centre](https://www.proteincentre.com/). During this time, I conducted numerous structural proteomics experiments for internally and externally-driven research projects, and have collaborated with colleagues to develop novel technologies and methods. Our efforts have significantly contributed to multiple [publications](https://scholar.google.ca/citations?user=W0-D1aYAAAAJ) in peer-reviewed journals.

Beyond the "wet-lab" I cultivated an affinity for programming and software development, realising their potential to enhance analyses in my field. In my most recent role I gained experience in the emerging field of proteogenomics, which combines proteomics and genomics to gain a more comprehensive understanding of protein expression and (dys)function. As someone with a passion for leveraging cutting-edge technologies, I am thrilled to be expanding my expertise in this exciting area of research and I had the chance to create R-based tools for proteogenomic applications. This deepened my understanding of genomics and expanded my perspective to encompass a wider range of multiomic investigations in biological research.

Looking ahead, my compass is set on harnessing my skillset and years of experience in structural proteomic analyses and bioinformatics to drive the advancement of biological understanding, groundbreaking technologies, and new therapeutic solutions.

```{r}
#| echo: false
emo::ji("smile")
```
